##[时间设置]
##当方块不在列表第一个时
##插件就会开启倒计时
##当倒计时结束 方块会重新生成为列表的第一个
##
##单位：秒
## 20时间刻=1秒
##最低不超过0.05s


##插件注册服务器检测时间
##每个DetectTime会检测一次json文件
##不要设置低于0.5s
##这会消耗你的服务器内存与算力
DetectTime: 1
##当方块为列表的最后一个时 应该得到的倒计时
DeepBlockRegenTime: 10
##当方块为列表的中间部分时 应该得到的倒计时
##这个设置确保了不会出现一片区域全是列表中间部分的方块
MiddleBlockRegenTime: 30