name: BlockRegen
version: '${project.version}'
main: cn.saltedfish.blockregen.BlockRegen
api-version: '1.20'
description: This plugin allows for the regeneration of block after it has been mined.
authors: [Pokiee]
website: https://github.com/PokieeAngNown/BlockRegen
commands:
  blockregen:
    description: Main command in this plugin.